### ISSUE TITLE
Get the IDE report exception dialog to report to GitHub issues

### ISSUE THREAD

**Issue by nbransby** [TeamHubApp/intellij-plugin#2]
Would like this dialog to have the button 'Report to TeamHub' which creates an issue in this repository complete with all the details from the report.

![image](https://user-images.githubusercontent.com/1386607/48959722-937e5480-ef67-11e8-90da-2f855739fe79.png)

Its this class in the platform sdk that is relevant:

https://github.com/JetBrains/intellij-community/blob/master/platform/platform-api/src/com/intellij/openapi/diagnostic/ErrorReportSubmitter.java

Not much docs on it but these might be useful:

https://intellij-support.jetbrains.com/hc/en-us/search?utf8=%E2%9C%93&topic=200366979&query=ErrorReportSubmitter+

---
There is a **$50 open bounty** on this issue.

**Comment by ice1000** [comment]
`$50`! #9 I can help with this, can I get `$50` by helping you implement this?

**Comment by nbransby** [comment]
@ice1000 hey, I think @RedMillLtd has got this one but maybe you want to help out with on of the other issues? Like this one: https://github.com/TeamHubApp/intellij-plugin/issues/3
